"""CI template generation (``bewit ci gitlab``).

CI is the enforcement backstop that needs zero developer adoption: the
rules run against every merge request regardless of what is installed on
laptops. The generated template contains two jobs:

- ``bewit:rules`` — required gate: scans the MR diff against path rules,
  runs quality-check commands, and verifies the tamper-evidence chain of
  committed session logs. Fails the pipeline on block-level findings.
- ``bewit:mr-report`` — best-effort provenance: renders the session
  report for the MR's head commit (found via the Bewit-Session commit
  trailer) and posts it as an MR comment when a token is configured;
  otherwise the report lands in the job artifacts.
"""

from __future__ import annotations

from pathlib import Path

from bewit import __version__

GITLAB_TEMPLATE = """\
# Bewit CI - generated by `bewit ci gitlab`. Reference #<issue> in MRs.
#
# Include from your .gitlab-ci.yml:
#   include:
#     - local: @INCLUDE_PATH@
#
# Optional: set BEWIT_GITLAB_TOKEN (a project access token with `api`
# scope, masked CI variable) to post session reports as MR comments.
#
# Install source: BEWIT_PIP_SPEC is pinned to the Bewit version that
# generated this file. Override it as a project CI/CD variable (which takes
# precedence over these defaults) for a private index or a git URL pinned to
# a commit, e.g. git+https://gitlab.example.com/tools/bewit.git@<sha>.
# Never use an unpinned name: an unpinned install runs whatever the index
# serves under that name, with access to this pipeline's variables.

.bewit:base:
  stage: test
  image: python:3.12-slim
  interruptible: true
  variables:
    BEWIT_PIP_SPEC: "@BEWIT_PIP_SPEC@"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

bewit:rules:
  extends: .bewit:base
  before_script:
    - apt-get update -qq && apt-get install -y -qq git > /dev/null
    - pip install --quiet "$BEWIT_PIP_SPEC"
    - git fetch --quiet origin "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --depth=200
  script:
    # Path + quality rules over the MR's changed files; exits 1 on
    # block-level findings. Install your analyzers (semgrep, eslint, ...)
    # here when check rules reference them.
    - bewit check diff --base "origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    # Tamper evidence: session event logs must have intact chains. With
    # record_store: ref the records live on their own ref: fetch it first.
    - git fetch --quiet origin "+refs/bewit/records:refs/bewit/records" || true
    - bewit verify --all

bewit:mr-report:
  extends: .bewit:base
  allow_failure: true
  before_script:
    - apt-get update -qq && apt-get install -y -qq git curl > /dev/null
    - pip install --quiet "$BEWIT_PIP_SPEC"
  script:
    # record_store: ref keeps session records on their own ref; fetch it
    # (a no-op for repositories that commit records with the code).
    - git fetch --quiet origin "+refs/bewit/records:refs/bewit/records" || true
    # The commit trailer links this MR's head commit to its agent session.
    - SESSION=$(git log -1 --format=%B | sed -n 's/^Bewit-Session:[[:space:]]*//p' | head -1)
    - echo "Session for $CI_COMMIT_SHORT_SHA: ${SESSION:-<none>}"
    - |
      if [ -n "$SESSION" ]; then
        bewit show "$SESSION" --md -o bewit-report.md
      else
        echo "No Bewit session linked to this commit." > bewit-report.md
      fi
    - |
      if [ -n "$BEWIT_GITLAB_TOKEN" ]; then
        curl --silent --request POST \\
          --header "PRIVATE-TOKEN: $BEWIT_GITLAB_TOKEN" \\
          --data-urlencode "body@bewit-report.md" \\
          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes" > /dev/null \\
          && echo "Report posted as MR comment."
      else
        echo "BEWIT_GITLAB_TOKEN not set - report kept as artifact only."
      fi
  artifacts:
    when: always
    paths:
      - bewit-report.md
    expire_in: 30 days
"""


def write_gitlab_template(root: Path, output: Path | None = None) -> Path:
    """Write the GitLab CI template into the repository; returns the path.

    The jobs install exactly this Bewit release (``bewit==<version>``)
    unless the project overrides ``BEWIT_PIP_SPEC``.
    """
    target = output or (root / ".gitlab" / "bewit-ci.yml")
    include_path = target.relative_to(root).as_posix() if target.is_relative_to(root) else target.as_posix()
    target.parent.mkdir(parents=True, exist_ok=True)
    # Plain replacement, not str.format: the template is full of shell and
    # GitLab ${...} braces that format() would misread as placeholders.
    content = GITLAB_TEMPLATE.replace("@INCLUDE_PATH@", include_path).replace(
        "@BEWIT_PIP_SPEC@", f"bewit=={__version__}"
    )
    target.write_text(content, encoding="utf-8", newline="\n")
    return target
