"""CI template generation (``archrev ci gitlab``).

CI is the enforcement backstop that needs zero developer adoption: the
rules run against every merge request regardless of what is installed on
laptops. The generated template contains two jobs:

- ``archrev:rules`` — required gate: scans the MR diff against path rules,
  runs quality-check commands, and verifies the tamper-evidence chain of
  committed session logs. Fails the pipeline on block-level findings.
- ``archrev:mr-report`` — best-effort provenance: renders the session
  report for the MR's head commit (found via the ArchRev-Session commit
  trailer) and posts it as an MR comment when a token is configured;
  otherwise the report lands in the job artifacts.
"""

from __future__ import annotations

from pathlib import Path

GITLAB_TEMPLATE = """\
# ArchRev CI - generated by `archrev ci gitlab`. Reference #<issue> in MRs.
#
# Include from your .gitlab-ci.yml:
#   include:
#     - local: @INCLUDE_PATH@
#
# Optional: set ARCHREV_GITLAB_TOKEN (a project access token with `api`
# scope, masked CI variable) to post session reports as MR comments.

archrev:rules:
  stage: test
  image: python:3.12-slim
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - apt-get update -qq && apt-get install -y -qq git > /dev/null
    - pip install --quiet archrev
    - git fetch --quiet origin "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" --depth=200
  script:
    # Path + quality rules over the MR's changed files; exits 1 on
    # block-level findings. Install your analyzers (semgrep, eslint, ...)
    # here when check rules reference them.
    - archrev check diff --base "origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
    # Tamper evidence: committed session event logs must have intact chains.
    - archrev verify --all

archrev:mr-report:
  stage: test
  image: python:3.12-slim
  interruptible: true
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - apt-get update -qq && apt-get install -y -qq git curl > /dev/null
    - pip install --quiet archrev
  script:
    # The commit trailer links this MR's head commit to its agent session.
    - SESSION=$(git log -1 --format=%B | sed -n 's/^ArchRev-Session:[[:space:]]*//p' | head -1)
    - echo "Session for $CI_COMMIT_SHORT_SHA: ${SESSION:-<none>}"
    - |
      if [ -n "$SESSION" ]; then
        archrev show "$SESSION" --md -o archrev-report.md
      else
        echo "No ArchRev session linked to this commit." > archrev-report.md
      fi
    - |
      if [ -n "$ARCHREV_GITLAB_TOKEN" ]; then
        curl --silent --request POST \\
          --header "PRIVATE-TOKEN: $ARCHREV_GITLAB_TOKEN" \\
          --data-urlencode "body@archrev-report.md" \\
          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes" > /dev/null \\
          && echo "Report posted as MR comment."
      else
        echo "ARCHREV_GITLAB_TOKEN not set - report kept as artifact only."
      fi
  artifacts:
    when: always
    paths:
      - archrev-report.md
    expire_in: 30 days
"""


def write_gitlab_template(root: Path, output: Path | None = None) -> Path:
    """Write the GitLab CI template into the repository; returns the path."""
    target = output or (root / ".gitlab" / "archrev-ci.yml")
    include_path = target.relative_to(root).as_posix() if target.is_relative_to(root) else target.as_posix()
    target.parent.mkdir(parents=True, exist_ok=True)
    # Plain replacement, not str.format: the template is full of shell and
    # GitLab ${...} braces that format() would misread as placeholders.
    target.write_text(
        GITLAB_TEMPLATE.replace("@INCLUDE_PATH@", include_path),
        encoding="utf-8",
        newline="\n",
    )
    return target
